### ISSUE TITLE
Orientation property of PWA

### ISSUE THREAD

**Issue by Novaliis** [GoogleChromeLabs/bubblewrap#309] opened 2020-09-01 07:06 UTC
Hi all,
I generated an APK (and I'm posting it to Google Play) from my PWA: [android.cromimi.com](https://android.cromimi.com)
I used PWABuilder which used Bubblewrap to generate an APK from my PWA

It seems that the generated APK does not respect the orientation of the PWA (landscape only).
Is there any way to solve the problem ?

Regards,
Benoît

**Comment by andreban** [comment] 2020-09-01 07:15
This looks like a duplicate of #281

**Comment by andreban** [comment] 2020-09-07 06:51
Closing as duplicate of #281

**Closed by andreban** 2020-09-07 06:51 UTC
Labels: duplicate, enhancement
