### ISSUE TITLE
Provide paths to JDK and Android tools and environment variables for automation

### ISSUE THREAD

**Issue by kross-italk** [GoogleChromeLabs/bubblewrap#172] opened 2020-05-14 15:01 UTC
**Is your feature request related to a problem? Please describe.**

Trying to set this tool up in a Docker container. There doesn't appear to be a way to provide the paths to the JDK and android tools via command line. Also being able to change these paths if I got them wrong?

**Describe the solution you'd like**

Is there a flag for providing these values? I looked around issues and noticed --sdk_root but that generated an error ("cli ERROR "--sdk_root=/opt/java/openjdk/bin/" is not a valid command!")

In addition to providing the JDK tools, can the entire process be automated? Currently I have to enter some details in the tool ("? Domain being opened in the TWA:") while this could all be inferred from the provided URL.

**Comment by PEConn** [comment] 2020-05-14 15:19
`bubblewrap` will read the JDK and Android SDK path from `~/llama-pack/llama-pack-config.json` if it is available. Example file:

```
{
    "jdkPath":"/usr/lib/jvm/java-11-openjdk-amd64",
    "androidSdkPath":"/home/peconn/Android/Sdk"
}
```

Does that work for you? (We still may want to see to this feature request.)

Also, @andreban we should probably update that path to `./bubblewrap/bubblewrap-config.json`.

**Comment by andreban** [comment] 2020-05-14 15:35
We're tracking changing the name in #159

An alternative would be using environment variables for the paths. 

We already have `BUBBLEWRAP_KEYSTORE_PASSWORD` and `BUBBLEWRAP_KEY_PASSWORD` for the keystore passwords.

**Comment by kross-italk** [comment] 2020-05-14 16:17
@PEConn I copied in that file and confirmed it is available (I'm running as root so it's /root/llama-pack/llama-pack-config.json) 
My run command is bubblewrap init --manifest <url>
It still prompts for the path to JDK

**Comment by andreban** [comment] 2020-05-14 16:39
@kross-italk Let me know if you plan on publishing the docker container. That sounds quite interesting, and an idea would be making the setup available in this repo as well.

**Comment by andreban** [comment] 2020-08-11 18:53
Duplicate of #222

**Closed by andreban** 2020-08-11 18:53 UTC
Labels: enhancement
