### ISSUE TITLE
Whitescreen when launching PWA (TWA) on chromebook

### ISSUE THREAD

**Issue by hltvlyx** [GoogleChromeLabs/bubblewrap#52] opened 2019-12-17 11:33 UTC
When launching the app which has been compiled through `llama-pack`, only a white screen will appear and make the computer sluggish (it seems as it's trying to open a new tab multiple times).

How can I debug this further? Since it's a compiled app now, I cannot access the chrome dev tools.

**Comment by PEConn** [comment] 2019-12-17 11:41
Hey hltvlyx,

Would it be possible for you to provide a video of you trying to launch the TWA and what happens?

We're working on providing proper ChromeOS support for TWAs (which for a TWA generated from llama-pack would install the website as a Desktop PWA). I've duplicated this bug in Chrome's bug tracker to get comments from the ChromeOS folks: https://crbug.com/1034933 who would can probably help you debug this.

**Comment by hltvlyx** [comment] 2019-12-17 12:07
> Hey hltvlyx,
> 
> Would it be possible for you to provide a video of you trying to launch the TWA and what happens?
> 
> We're working on providing proper ChromeOS support for TWAs (which for a TWA generated from llama-pack would install the website as a Desktop PWA). I've duplicated this bug in Chrome's bug tracker to get comments from the ChromeOS folks: https://crbug.com/1034933 who would can probably help you debug this.

Hey!
I've attached a video here: [pwa-twa-white-screen.mp4.zip](https://github.com/GoogleChromeLabs/llama-pack/files/3973176/pwa-twa-white-screen.mp4.zip)

Awesome, thanks for creating the bug report there as well!

**Comment by dominickng** [comment] 2019-12-18 03:07
Which Chrome OS channel are you on? If you're on one of the prerelease channels, this is expected behaviour (CCT / TWA support is in development and nowhere near finished).

If you're on stable, this should open a tab in Chrome browser. Let us know which is the case and we can follow up.

**Comment by hltvlyx** [comment] 2019-12-18 07:27
> Which Chrome OS channel are you on? If you're on one of the prerelease channels, this is expected behaviour (CCT / TWA support is in development and nowhere near finished).
> 
> If you're on stable, this should open a tab in Chrome browser. Let us know which is the case and we can follow up.

Using Chrome OS v.80.0.3987.0 (64-bit). Also on `dev` channel.

**Comment by dominickng** [comment] 2019-12-19 06:04
Yes, then this is expected. If you try the stable channel, it should open a new tab in the browser since we don't (yet) fully support TWAs. We're working on it though.

**Comment by hltvlyx** [comment] 2020-02-17 07:27
Since issue #88 is now closed, would this presumably be fixed now?

**Comment by andreban** [comment] 2020-03-01 15:00
Implementation on the Chrome side hasnt landed yet. We shouldn't need
anymore changes on llama-pack though.

**Comment by hazae41** [comment] 2020-04-15 18:40
How do the new Twitter app open itself as a PWA? Same with Maps Go

**Comment by andreban** [comment] 2020-10-29 19:14
Closing this, as TWAs are now supported in Chromebooks.

**Closed by andreban** 2020-10-29 19:14 UTC
Labels: bug, depends-external
