### ISSUE TITLE
Issue in bubblewrap build command 

### ISSUE THREAD

**Issue by Supritha0203** [GoogleChromeLabs/bubblewrap#833] opened 2023-10-25 06:04 UTC
When the bubblewrap build command is executed, it shows the following error
Installing Android Build Tools. Please, read and accept the license agreement.
build Installing Build Tools
Error: Could not find or load main class s
Caused by: java.lang.ClassNotFoundException: s

cli ERROR undefined
The jdk and android sdk are downloaded from the bubblewrap itself
![Screenshot 2023-10-25 113341](https://github.com/GoogleChromeLabs/bubblewrap/assets/102866536/786006e3-1c63-4fcb-b72f-d9a45f7f7a1d)

**Comment by emoffett** [comment] 2023-12-31 09:50
I experienced the same issue

**Comment by designerjason** [comment] 2024-04-05 08:47
This issue has been around for quite a while... https://github.com/GoogleChromeLabs/bubblewrap/issues/606

**Comment by ibrahimkarahan** [comment] 2024-04-08 20:06
Duplicate of #606

**Closed by ibrahimkarahan** 2024-04-08 20:06 UTC
