### ISSUE TITLE
Bubblewrap update is deleting files

### ISSUE THREAD

**Issue by AlissonRS** [GoogleChromeLabs/bubblewrap#431] opened 2021-01-03 03:28 UTC
**Describe the bug**
`bubblewrap update` is deleting files we added manually, including resource files and java classes. Also, it's recreating CLI generated files like `LauncherActivity.java`, `DelegationService.java`, `gradle.properties`.

**To Reproduce**
Run `bubblewrap update` in the root directory.

**Expected behavior**
It shouldn't delete files we created manually.
It should check if files generated by the CLI already exist (e.g `LauncherActivity.java`), and either prompt the user if they want to override these files. Another idea is to just ignore and skip files that already exist, in this way we can just manually delete any files that we wanted to be recreated by the CLI.

**Screenshots**
Git Changes after running `bubblewrap update`, for reference:

![image](https://user-images.githubusercontent.com/4753901/103471011-4a5d7900-4d59-11eb-82d2-6477df2b2d86.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
The reason `update` should behave like this is because sometimes we need to add custom logic into the TWA app, for example when we need to use some native android API that is not supported by PWAs yet.

**Comment by andreban** [comment] 2021-01-03 09:21
Thanks for filing the issue, but this is working as intended - if you want to do updates to the project directly, you won't be able to use `update`.  In this case, I'd consider moving the project to Android Studio, as you'll get better support for editing the project.

Another point is: could the customisations your are making to the project be part of a Bubblewrap configuration? I'll close this issue, as it's working as intended, but feel free to open feature-requests for customisations you are making that could make sense in Bubblewrap.

Obrigado

**Closed by andreban** 2021-01-03 09:21 UTC

**Comment by AlissonRS** [comment] 2021-01-04 03:05
Hi @andreban 

Thanks for your reply. It turns out not all customisations are part of Bubblewrap config like the `DelegationService` which can easily be enabled by changing a flag in the twa-manifest.json. Are you saying Bubblewrap is not designed to be used alongside Android Studio? So if we need custom logic not supported by PWAs/Bubblewrap, we need to just give up using Bubblewrap?

I saw the code for [update.ts](https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/cli/src/lib/cmds/update.ts#L51) and it basically deletes everything and create from scratch with the incremented version. In my opinion this is not how an `update` should work, hence I opened this as a bug.

If you're not willing to change how it works, then I'd suggest to at least warn the user and ask for confirmation, something like:

> This command will delete all files in this project and create from scratch. Any changes in this project not done by Bubblewrap CLI will be lost, including new files. Do you want to continue? Y/N

I was lucky my code was already checked in, but maybe future users won't be that lucky, so I think at least the warning would be nice.

If you agree I can open as a new feature request.

Thanks,
Alisson

**Comment by andreban** [comment] 2021-01-05 11:14
> Are you saying Bubblewrap is not designed to be used alongside Android Studio? So if we need custom logic not supported by PWAs/Bubblewrap, we need to just give up using Bubblewrap?

Yes, this is correct - to enable using Bubblewrap alongside Android Studio, Bubblewrap would have to be able to understand changes made to the project via Android Studio, which would be prohibitively complicated. Besides, the goal with Bubblewrap is to enable developers who don't want to or don't know how to use Android Studio to easily create an APK from their PWA (and keep it up to date), se this would likely be outside the scope of the project too. 

It's definitely possible to bootstrap a project with Bubblewrap and then continue on Android Studio, but the opposite is not true. Maybe this should be more clear in the docs - I don't think a warning before update is the way to go, as we developers using Bubblewrap shouldn't have to care about the Android project code.

**Comment by AlissonRS** [comment] 2021-01-05 23:42
@andreban that makes sense.

In fact I'm one of these developers that didn't know how to use Android Studio (nor wanted to), but I needed to implement something (using `NotificationListenerService` to read all notifications and SMS) that is currently not supported by the Android Browser Helper lib.

I can open a feature request in their repo, I would be keen on making a PR (and later here on Bubblewrap to use this new activity as a toggleable config), but I don't think it could be easily implemented tbh, and I'm not sure they would want this as not enough people would use this anyway.

Thanks for taking your time to explain everything!!!

**Comment by andreban** [comment] 2021-01-06 10:11
I have updated the [documentation for `update` ](https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#update) with a warning. I hope this helps others.

Regarding reading SMS, is this the case you need to listen for an OTP code? If that's the case, you'll could use the [Web OTP API](https://web.dev/sms-receiver-api-announcement/) instead. Otherwise, it might be interesting to understand the use-case better and see if there's any upcoming API that's part of [Project Fugu](https://web.dev/fugu-status/) that can help.

**Comment by AlissonRS** [comment] 2021-01-06 14:27
@andreban thanks for updating the docs, hopefully it'll help others.

In my use-case, we have an app to help people manage their budget (expenses/income). We wanted to read notifications/sms, so when we detect one containing value/money (e.g bank notification), we add our own notification suggesting the user to "import" that expense/income into our app. Clicking our notification will open our app with the form filled with description, value, etc. Some similar apps offer this capability, so we thought we should support this too.

In short, the way we implemented this as of now:

- Launch web activity using query params to tell PWA it's running within Android + permission is not granted yet;
- Display some UI asking the user to give permission and explaining how it can be helpful;
- When user clicks the button, we use Web Share API to trigger an explicit intent in our Android App;
- We run `startActivityForResult(new Intent(ACTION_NOTIFICATION_LISTENER_SETTINGS), REQUEST_CODE)`
- On result, we check if permission has been granted, then restart the app

We're willing to rewrite all this stuff if there is an easier approach, but I couldn't find any sort of interoperability (e.g through intents, web share or APIs) with banking systems.
