### ISSUE TITLE
Splash screen icon size

### ISSUE THREAD

**Issue by vitorqueirosz** [GoogleChromeLabs/bubblewrap#804] opened 2023-06-20 18:47 UTC
When opening an android app built with bubblewrap, the splash screen icon is huge, specially for small/medium devices.

Looking at the code, the splash screen icon size goes from 300 to 1200, these shouldn't be the sizes of a splash screen icon.

```js
const SPLASH_IMAGES: IconDefinition[] = [
  {dest: 'app/src/main/res/drawable-mdpi/splash.png', size: 300},
  {dest: 'app/src/main/res/drawable-hdpi/splash.png', size: 450},
  {dest: 'app/src/main/res/drawable-xhdpi/splash.png', size: 600},
  {dest: 'app/src/main/res/drawable-xxhdpi/splash.png', size: 900},
  {dest: 'app/src/main/res/drawable-xxxhdpi/splash.png', size: 1200},
];
```

Is it possible to generate the splash screen icons in a lower dimension?

it could be these dimensions

```
MDPI icon-48x48, splash-470x320

HDPI icon-72x72, splash-640x480

XHDPI icon-96x96, splash-960x720

XXHDPI icon-144x144

XXXHDPI icon-192x192
```

**Comment by AllanOliveiraM** [comment] 2023-07-04 03:59
UP

for me too, it's an important point in my application
for most of my clients the logo is huge on the splash screen

**Comment by andreban** [comment] 2023-08-01 09:40
Duplicate of https://github.com/GoogleChromeLabs/bubblewrap/issues/226.

**Closed by andreban** 2023-08-01 09:40 UTC
