### ISSUE TITLE
cli ERROR 6:7: unexpected close tag

### ISSUE THREAD

**Issue by kapilkathuria** [GoogleChromeLabs/bubblewrap#645] opened 2022-01-26 04:39 UTC
I am seeing "cli ERROR 6:7: unexpected close tag". how do i figure out why is this error occurring? is verbose logging available to debug this further?

I have given more details below. I am running ubuntu in wsl on windows 10. https://forum.enkindle.guide/manifest.json is accessible over internet if you like try yourself.

```
$ bubblewrap --version
,-----.        ,--.  ,--.  ,--.
|  |) /_,--.,--|  |-.|  |-.|  |,---.,--.   ,--,--.--.,--,--.,---.
|  .-.  |  ||  | .-. | .-. |  | .-. |  |.'.|  |  .--' ,-.  | .-. |
|  '--' '  ''  | `-' | `-' |  \   --|   .'.   |  |  \ '-'  | '-' '
`------' `----' `---' `---'`--'`----'--'   '--`--'   `--`--|  |-'
                                                           `--'
version 1.15.0

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal

$ bubblewrap init --manifest https://forum.enkindle.guide/manifest.json
.
.
.
Generating Android Project.
 >> [██████████████████████░░░░░░░░░░░░░░░░░░] 55%

cli ERROR 6:7: unexpected close tag.
```

**Comment by PEConn** [comment] 2022-01-26 10:48
Unfortunately there isn't a verbose flag for you to use, however I was able to reproduce and have a go at debugging it. The issue is that https://forum.enkindle.guide/svg-sprite/forum.enkindle.guide/icon/222222/signal.svg uses a self closing tag (`<path ... />`). I'm not sure whether that's allowed or not by the standard, but it's tripping `svg2img` up, which is what we use for dealing with SVGs.

If you change that to have a closing `</path>` instead, hopefully things will work.

I'll also add some context to the error to make it a bit clearer what was failing.

**Closed** 2022-03-24 20:55 UTC
