### ISSUE TITLE
build fails with "The system cannot find the path specified" on Windows 

### ISSUE THREAD

**Issue by amanintech** [GoogleChromeLabs/bubblewrap#147] opened 2020-05-01 19:07 UTC
I am trying `bubblewrap `on windows nodejs v12.10.0

This is how my llama-pack config looks like where I have directed it to latest android cli and OpenJDK directory

`{"jdkPath":"D:\\work\\openjdk","androidSdkPath":"D:\\work\\and-cli"}`

This the error it returns
```
bubblewrap build
Installing Android Build Tools. Please, read and accept the license agreement
Installing Build Tools
The system cannot find the path specified.


cli ERROR undefined
```
I have already done the init which worked fine but build is not working

**Comment by andreban** [comment] 2020-05-01 19:41
Could you confirm the version of Bubblewrap being used? It'd be great if you could confirm the version of the android-cli-tools being used too, as this may be related to this issue: https://issuetracker.google.com/issues/154298380

**Comment by andreban** [comment] 2020-05-01 19:48
It seems Bubblewrap is being unable to execute `sdkmanager`.  it should be located inside `D:\\work\\and-cli\\tools\\bin`. Can you check if it exists in that directory?

**Comment by andreban** [comment] 2020-05-01 20:09
I checked running with a folder without `/tools/bin/sdkmanager` and I can reproduce the error. My guess is that the android CLI tools was unzipped incorrectly (eg: maybe it unzipped the content into a sub-directory?)

While trying it out, I bumped into another issue on Windows, caused by the recent update to the Android CLI tools. I have created #148 to fix it.

**Comment by amanintech** [comment] 2020-05-02 15:32
> It seems Bubblewrap is being unable to execute `sdkmanager`. it should be located inside `D:\\work\\and-cli\\tools\\bin`. Can you check if it exists in that directory?

Yes It does ,

So whats the final resolution

**Comment by andreban** [comment] 2020-05-03 09:26
No final resolution yet. I need to be able to reproduce the issue in order to fix it. Any further details on your environment setup that could help?

**Comment by andreban** [comment] 2020-05-03 11:39
The code calls`sdkmanager` instead of `sdkmanager.bat`. It does work on my install. I wonder if that's the culprit.

@amanintech If you run `D:\work\and-cli\tools\bin\sdkmanager` on the command-line, what output do you get? Is it different from running `D:\work\and-cli\tools\bin\sdkmanager.bat`?

@JotinhaBR Could you try it too?

**Comment by JotinhaBR** [comment] 2020-05-03 11:49
@andreban 

this is my return:
![image](https://user-images.githubusercontent.com/6248317/80913435-fb1efe80-8d1a-11ea-8d79-6435e32c2c62.png)

**Comment by andreban** [comment] 2020-05-03 11:59
Ok, that last error seems related to this: https://issuetracker.google.com/issues/154298380, which is a bug on the Android SDK client. It seems unzipping the SDK with the `Extract All...` from Windows creates the wrong directory structure. Unzipping with something like [7-zip](https://www.7-zip.org/download.html) creates the correct structure. Can you try unzipping with 7-zip and check if that fixes the issue?

**Comment by JotinhaBR** [comment] 2020-05-03 12:15
@andreban 
I did the file extraction with 7-zips, even going straight to disk C to not have space, but I still have the same error.
![image](https://user-images.githubusercontent.com/6248317/80913906-877ef080-8d1e-11ea-875d-1277686b37e3.png)
![image](https://user-images.githubusercontent.com/6248317/80913921-982f6680-8d1e-11ea-976c-0b7311b4b6e2.png)
![image](https://user-images.githubusercontent.com/6248317/80913917-8f3e9500-8d1e-11ea-9759-e6ea99e60381.png)

**Comment by andreban** [comment] 2020-05-03 12:21
Oh, I see -> the Android CLI tools needs to be extracted to a folder. For instance: `C:\android-cli-tools`. The `\tools` directory will be inside that.  It need to be like that because when you run the tools it will create more files in that folder. `llama-pack-config.json` needs to point to `C:\\android-cli-tools`.

**Comment by JotinhaBR** [comment] 2020-05-03 12:32
@andreban 

Now it worked :)

Conclusion, the space does not get in the way, but the Android folder is protected for ADM only, so it’s not a good idea to put the SDK there, so I put it in the root C disk, and made the structure that spoke.

following prints:
![image](https://user-images.githubusercontent.com/6248317/80914276-e80f2d00-8d20-11ea-8b4a-f0f743234819.png)
![image](https://user-images.githubusercontent.com/6248317/80914282-feb58400-8d20-11ea-926e-ac1b1eee9ba7.png)


thank you :)

**Comment by andreban** [comment] 2020-05-03 12:37
@JotinhaBR glad to hear that!

@amanintech let me know if the same solution applies to you or if you are running into a different issue.

**Comment by amanintech** [comment] 2020-05-03 12:54
@andreban that indeed worked 
But Now it gives me this error 
![image](https://user-images.githubusercontent.com/28403318/80914718-0b5eca00-8d6b-11ea-969b-ddfb6fad58ff.png)
![image](https://user-images.githubusercontent.com/28403318/80914725-1154ab00-8d6b-11ea-8df5-d8dbc632a86e.png)


This is my environment configuration -
windows 10 x64
android CLI - 6200805_latest
OpenJDK -8

**Comment by andreban** [comment] 2020-05-03 13:01
@amanintech This seems like the issue fixed via #148. Version `1.1.2` of [@bubblewrap/cli](https://www.npmjs.com/package/@bubblewrap/cli) has been released and should have the fix. Can you check if you are on version `1.1.2`?

**Comment by amanintech** [comment] 2020-05-03 13:10
@andreban Yes that's true updating to `1.1.2` fixed the issue.

Also, I think we should update the quick setup guide to suggest them to add android-cli tools to the tools folder.

**Comment by andreban** [comment] 2020-05-03 13:25
@amanintech thanks for confirming!

+1 on improving the quick setup guide. It's probably worth creating an issue to track this. Also, contributions (docs and code) are greatly appreciated. 😉

**Comment by amanintech** [comment] 2020-05-03 13:29
I would to fix that and already have  Created issue #155 
Please assign that to me

**Closed** 2020-05-03 13:30 UTC
Labels: bug

**Comment by rohitattaluri** [comment] 2020-08-25 15:58
OS: Windows 10
Node: v12.16.1
bubblewrap: v1.5.0


![image](https://user-images.githubusercontent.com/59006955/91197776-5b4a0e00-e719-11ea-8754-738536515af8.png)


This is the error I'm getting while running **bubblewrap build**
I've downloaded and unzipped **commandlinetools** for android but still its pointing to Android Studio application.

need some help to solve this asap.

**Comment by amanintech** [comment] 2020-08-25 19:44
@rohitattaluri Did, you tried following the exact steps at https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli ?

**Comment by rohitattaluri** [comment] 2020-08-26 04:44
> @rohitattaluri Did, you tried following the exact steps at https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli ?

thanks man. Actually I referred to some other doc's. Went to some Misinterpretation.

Thanks for the reference link. Followed it and works amazing.

**Comment by amanintech** [comment] 2020-08-26 05:55
Awesome 👏🏻
