### ISSUE TITLE
Splash screen Footer String doesn't not showing

### ISSUE THREAD

**Issue by sunBhabani** [GoogleChromeLabs/bubblewrap#365] opened 2020-10-14 04:04 UTC
Dear Support,

As informed by PWABuilder Team (JudahGabriel), PWABuilder relies on Google's Bubblewrap to create the splash screen during our online web based creating apk.

So, after build the APK using 'PWABuilder', when the APP lunch on a handset/emulator, the beginning Splash Screen only display the Image. Not showing the footer Text. Actually It's not obey the Manifest string. I have attached an image which illustrated the splash screen difference between the normal 'ServiceWorker' prompt installation & a Play-Store installation.
image

![image](https://user-images.githubusercontent.com/70555988/95942118-fe590300-0dff-11eb-8362-b7de16c0569f.png)

**Comment by andreban** [comment] 2020-10-14 13:42
@sunBhabani, the bottom text is part of WebApks (eg: a PWA added to the homescreen). #66 has a more complete list of differences.

**Comment by andreban** [comment] 2021-04-14 11:22
Closing this as working as intended, since there's no API in Trusted Web Activity to add a text.

**Closed by andreban** 2021-04-14 11:22 UTC
Labels: depends-external, enhancement
