### ISSUE TITLE
Share target is not supported

### ISSUE THREAD

**Issue by greyGuy11** [GoogleChromeLabs/bubblewrap#298] opened 2020-08-24 12:13 UTC
I have got declared share_target in manifest.json. As PWA it works perfectly.
For app generated via bubblewrap it doesn't work.

**Comment by andreban** [comment] 2020-08-24 12:38
There's work that needs to happen on android-browser-helper before Bubblewrap supports it. You can check progress here: https://github.com/GoogleChrome/android-browser-helper/issues/66

**Comment by andreban** [comment] 2020-10-29 19:06
Duplicate of #21

**Closed by andreban** 2020-10-29 19:06 UTC
Labels: depends-external, enhancement
