### ISSUE TITLE
Provide keystore passwords from a file

### ISSUE THREAD

**Issue by kross-italk** [GoogleChromeLabs/bubblewrap#187] opened 2020-05-28 14:05 UTC
**Is your feature request related to a problem? Please describe.**
Hey it's Kyle from #172. I've created a working docker container that is able to build with manual intervention. I'm putting together some automation scripts to put this in our CI pipeline. I'm stuck trying to enter passwords in the `bubblewrap build` step. 

**Describe the solution you'd like**
I'd like to put my key passwords in a file or have them read from the environment. 

**Describe alternatives you've considered**
I can automate the `bubblewrap init` step by piping  `yes ''`. If passwords were read ahead of time, the build step could be automated too. 

**Additional context**
We're planning to commit the Docker and Makefiles back to this repo as requested! Thanks so much for the help last time.

**Comment by andreban** [comment] 2020-05-28 14:11
Hi Kyle,

It's possible to set the passwords as environment variables `BUBBLEWRAP_KEYSTORE_PASSWORD` and `BUBBLEWRAP_KEY_PASSWORD`. Does this help?

**Comment by kross-italk** [comment] 2020-05-28 14:12
Awesome, I'll give that a try. Is there some documentation I'm missing? I'm following this guide
https://developers.google.com/web/android/trusted-web-activity/quick-start

**Comment by andreban** [comment] 2020-05-28 14:18
The place to document it would be https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/cli/README.md. But we don't have it there yet. 

Probably a section on "Automated Builds"

**Comment by kross-italk** [comment] 2020-05-28 14:40
Thanks again. For reference, what are all the environment variables recognized? I wonder if there are more graceful solutions than `yes ''`

**Comment by andreban** [comment] 2020-05-28 15:09
Those are the only ones for now

**Comment by andreban** [comment] 2020-08-11 18:44
#276 adds the missing information to the docs

**Comment by andreban** [comment] 2020-08-11 18:53
Duplicate of #222

**Closed by andreban** 2020-08-11 18:53 UTC
Labels: enhancement
