### ISSUE TITLE
Could not find or load main class Files

### ISSUE THREAD

**Issue by AkhilNaidu09** [GoogleChromeLabs/bubblewrap#223] opened 2020-07-04 19:22 UTC
**I was trying to build using bubblewrap and getting following error**
**Could not find or load main class Files**

![image](https://user-images.githubusercontent.com/13352708/86519594-66c93900-be3c-11ea-85a2-925282bd6b8a.png)

Can you please help me what i am doing wrong.

**Comment by andreban** [comment] 2020-07-05 08:13
It seems your `androidSdkPath` is pointing to the JDK. This section of the docs explain how to update manually: https://github.com/GoogleChromeLabs/bubblewrap/tree/master/packages/cli#updating-the-location-of-the-jdk-and--or-the-android-command-line-tools.

We're working on a `doctor` command that will make debugging this easier. Marking as a duplicate of that issue. 

Duplicate of #181

**Closed by andreban** 2020-07-05 08:13 UTC

**Comment by andreban** [comment] 2020-07-05 08:15
Duplicate of #181

**Comment by jamieoneill** [comment] 2020-07-09 13:16
Following https://developers.google.com/web/android/trusted-web-activity/quick-start

I got the same error. Android SDK path was definitely pointing to correct location after downloading the cli tools.
In the end had to install android studio and point to the paths relative to that installation.

```json
{"jdkPath":"C:\\Program Files\\Android\\Android Studio\\jre",
"androidSdkPath":"C:\\Users\\jamie\\AppData\\Local\\Android\\Sdk"}
```

Not sure if the standalone cli tools is missing something bubblewrap depends on.

@andreban can you test a pc without android studio with that tutorial to recreate issue?

**Comment by andreban** [comment] 2020-07-09 13:31
In the case of the original issue, you can see the program is looking for `sdkmanager.bat`, which is part of the Android CLI tools under the `AdoptOpenJDK` folder, which is where the JDK is located. It seems, in that case, the paths were mixed, which caused the issue.

We frequently test without Android Studio as that's how we expect developers to use. If you provide details on the configuration that was failing for you (the one posted is what actually works?), including JDK and android command line tool versions, that would be helpful.

**Comment by jamieoneill** [comment] 2020-07-09 13:57
ah i didnt notice the original issues path...

Correct paths posted above worked for me.

As for whats failing i can recreate

OS: win10
1. Install AdoptOpenJDK\jdk-8.0.252.09-hotspot
2. Download commandlinetools-win-6609375_latest.zip
3. Unzip cli tools to C:\Program Files (x86)\AndroidTools (fullpath example: C:\Program Files (x86)\AndroidTools\tools\bin)
4. bubblewrap init --manifest {my_url}/manifest.json
5. Input paths at prompt
```
{"jdkPath":"C:\\Program Files (x86)\\AdoptOpenJDK\\jdk-8.0.252.09-hotspot",
"androidSdkPath":"C:\\Program Files (x86)\\AndroidTools"}
```
6. bubblewrap build
![Capture](https://user-images.githubusercontent.com/5860973/87048849-27ac3680-c1f4-11ea-9968-50f13e31aa62.PNG)

**Comment by andreban** [comment] 2020-07-09 15:03
Gotcha - definitely a different error - I've had issues with spaces in the path to the Android CLI tools in the past (the android CLI tools don't really like it see [here](https://stackoverflow.com/questions/37052934/android-sdk-location-should-not-contain-whitespace-as-this-cause-problems-with)).

Would you mind trying to move the CLI tools to a path without spaces to check that?

**Comment by jamieoneill** [comment] 2020-07-09 15:09
Bingo, that's the exact issue... 
can we add a note to the readme? i can see people making the same mistake i did.

**Comment by andreban** [comment] 2020-07-09 15:10
Yes, we can also add this check to #181, which @chenlevy24 is working on.  @jamieoneill would you mind filing an issue for this?
