### ISSUE TITLE
App is freezing or crashing after some time 

### ISSUE THREAD

**Issue by nimit95** [GoogleChromeLabs/bubblewrap#130] opened 2020-03-24 13:47 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by andreban** [comment] 2020-03-24 14:27
Can you add more information to the issue, please? Is this a problem with the CLI interface or Without details on what is happening, device, browser version, etc, it is impossible to solve any issue.

**Comment by nimit95** [comment] 2020-03-25 12:19
Oh, sorry, I am talking about the android app. I tried in my phone(Oneplus 5t and android 9) and in my friends samsung galaxy s9. If the app is on the screen for like 3 min. It would either freeze or crash. Couldn't get the logs but should be easy to reproduce.

**Comment by nimit95** [comment] 2020-03-25 12:22
Also a great CLI tool overall :).
I initially put my JDK path wrong, it got saved in a llama config file. Took me a while to figure the config file out, as that file overrides ENV variables and twa manifest file. Will create a PR in readme or you would like me to create a fix in the code?

**Comment by andreban** [comment] 2020-03-25 12:55
Thanks for the update. Since the application freezes after ~3 minutes, my guess is that it is freezing while the Web app is open. Is that correct? If you open the same app in the browser, does it freeze?

Thanks for the feedback on the config. Contributions are always greatly appreciated, so if you want to send a PR for the readme or improving how the CLI works, you are welcome. I'd ask you to create an issue first, so we can discuss the problem and the solution. How does that sound?

**Comment by nimit95** [comment] 2020-03-25 13:06
Nope, when I open in the browser it doesn't freeze. It is very specific to the app created by CLI. Also, another observation I made was that if I switch between apps, CLI generated app and any other app. There are increased chances of a crash with a CLI app. And that doesn't happen with chrome on my mobile.

Cool will create a seprate issue for the same. Thanks.

**Comment by andreban** [comment] 2020-03-26 09:19
The app generated by the CLI is a wrapper that just launches a Trusted Web Activity, which is basically Chrome without an UI. I'd expect issues to happen when launching the app, but freezing after it's open is a bit odd. 

Nevertheless, since it's freezing inside the Trusted Web Activity, this looks more like a Chrome issue than a Bubblewrap one. Do you mind filing the bug on Chromium using [this template](https://code.google.com/p/chromium/issues/entry?summary=Issue%20Summary&comment=Application%20Version%20(from%20%22Chrome%20Settings%20%3E%20About%20Chrome%22):%20%0DAndroid%20Build%20Number%20(from%20%22Android%20Settings%20%3E%20About%20Phone/Tablet%22):%20%0DDevice:%20%0D%0DSteps%20to%20reproduce:%20%0D%0DObserved%20behavior:%20%0D%0DExpected%20behavior:%20%0D%0DFrequency:%20%0D%3Cnumber%20of%20times%20you%20were%20able%20to%20reproduce%3E%20%0D%0DAdditional%20comments:%20%0D&labels=OS-Android,Cr-UI-Browser-Mobile-CustomTabs), so we have it filed in the right place?

**Comment by andreban** [comment] 2020-04-14 11:22
Closing this, as this seems unrelated to Bubblewrap. Please, file the issue on Chromium with the template provided in the previous message if the issue persists.

**Closed by andreban** 2020-04-14 11:22 UTC
