### ISSUE TITLE
node-fetch fails to get manifest (because cert is newly issued?)

### ISSUE THREAD

**Issue by JudahGabriel** [GoogleChromeLabs/bubblewrap#330] opened 2020-09-09 23:03 UTC
**Describe the bug**
Running bubblewrap on https://ygc.istaka.store throws an error fetching the manifest.

**To Reproduce**
1. Run bubblewrap and send in https://ygc.istaka.store as the URL
2. You'll receive an error saying, "FetchError: request to https://ygc.istaka.store/manifest.json failed, reason: unable to verify the first certificate"

This bug was first filed [here](https://github.com/pwa-builder/PWABuilder/issues/1086) on the PWABuilder repo. I believe the error is coming from Bubblewrap itself, likely the [TwaManifest.fromWebManifest(...)](https://github.com/GoogleChromeLabs/bubblewrap/blob/master/packages/core/src/lib/TwaManifest.ts#L303) call. 

Doing some quick investigation, I see https://ygc.istaka.store has a valid HTTPS certificate according to Chrome and Edge. However, the HTTPS certificate was issued yesterday (Sept 8th 2020).

![image](https://user-images.githubusercontent.com/312936/92663177-62465400-f2b5-11ea-8ae2-0d126062619a.png)

Is the newness of this certificate causing an issue? Is there something Bubblewrap can do with its node-fetch calls to skip cert validation?

**Comment by andreban** [comment] 2020-09-10 07:32
It seems this is caused by the certificate not being correctly configured.  Here's what a [certificate checker](https://www.sslshopper.com/ssl-checker.html#hostname=https://ygc.istaka.store/) says: 
<img width="754" alt="Screen Shot 2020-09-10 at 08 24 22" src="https://user-images.githubusercontent.com/1733592/92694507-117b3d80-f33f-11ea-861d-afd1434e3107.png">

[This post on the LetEncrypt community](https://community.letsencrypt.org/t/the-certificate-is-not-trusted-in-all-web-browsers/77690) should explain how to fix it.

**Comment by andreban** [comment] 2020-09-10 08:19
As a note, this is not in the `node-fetch` implementation, but in the Node runtime itself. I'd recommend fixing the certificate, but it's possible to tell Node to ignore this::

```shell
export NODE_TLS_REJECT_UNAUTHORIZED=0
bubblewrap.js init --manifest=https://ygc.istaka.store/manifest.json
```

@JudahGabriel in the case of PWABuilder, this can be changed at runtime.
```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

There are more details on this [StackOverflow thread](https://stackoverflow.com/questions/52478069/node-fetch-disable-ssl-verification).

I'm closing the issue as, from a Bubblewrap perspective, things are working as intended.

**Closed by andreban** 2020-09-10 08:19 UTC

**Comment by JudahGabriel** [comment] 2020-09-10 19:21
Thanks, Andre!
