### ISSUE TITLE
TWA not updating when updated the manifest

### ISSUE THREAD

**Issue by sunBhabani** [GoogleChromeLabs/bubblewrap#342] opened 2020-09-23 11:41 UTC
Hi Support,

When the user has already installed the TWA, and when I updated the manifest (e.g. app name/short_name or name or background/theme color) and only then is the old app name/theme colors are still displayed on the user's device. This is the problem am facing in my TWA APP. The New Changes are not automatically apply on user's handset.

If i uninstall the APP and clear the Cache/History then the New Manifest details are showing.

My TWA site name is: https://scadalivex.net

Any help is deeply appreciated.

**Comment by andreban** [comment] 2020-09-23 11:45
Hi @sunBhabani,

Unfortunately, the native shell of the Trusted Web Activity can't be automatically updated - You'll need to update it, rebuild the app, and upload a new version to the Play Store.

Currently, you can updated it by modifying the values on the `twa-manifest.json` file, which was generated when creating the app, then calling `bubblewrap update` to apply those changes to the project, followed by `bubblewrap build` to generate a new package you can upload to the Play Store.

We're looking to streamline this process - the next step is automating updating values from the Manifest, which you can follow on #305 .

**Comment by andreban** [comment] 2020-10-14 13:43
Closing, as this is working as intended.

**Closed by andreban** 2020-10-14 13:43 UTC
Labels: wontfix
