### ISSUE TITLE
A private key has not been properly encrypted or is not a supported type.

### ISSUE THREAD

**Issue by JotinhaBR** [GoogleChromeLabs/bubblewrap#204] opened 2020-06-20 18:10 UTC
**Describe the bug**
I generated my key through bubblewrap, when I was generating my TWA and when I went to raise the key on Google Play Console, it keeps giving me this error:

![image](https://user-images.githubusercontent.com/6248317/85208572-f97bbb00-b307-11ea-8dd3-51f65b9e02a1.png)

**Comment by andreban** [comment] 2020-06-21 08:05
@JotinhaBR,

Play needs it in a different format than the one used to sign the app (which is what Bubblewrap's goal is):

- Have you exported the from Android Studio before uploading? 
- Otherwise, check the instructions on "Export and upload a key from a Java repository" (it's possible to export the key without Android Studio).

I also recommend reading the App Signing docs: https://support.google.com/googleplay/android-developer/answer/7384423

**Comment by andreban** [comment] 2020-06-23 13:05
Close this one as it's working as intended. File #208 for adding support to export keys.

**Closed by andreban** 2020-06-23 13:05 UTC
